name: TestDriver.ai - Empty Charts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  test:
    name: "TestDriver - Empty Charts"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testtestdriver
        with:
          prompt: |
            1. navigate to 'pubnub.com'
            2. click: LOGIN
            3. focus the email field and type: ${{ secrets.LOGIN_EMAIL }}
            4. focus the password field and type: ${{ secrets.LOGIN_PASSWORD }}           
            5. press Return on the keyboard to submit the form
            6. click Apps in the left nav
            7. click My First App
            8. click Demo Keyset
            9. click Usage & Monitoring
            10. scroll and look at all the charts, confirm there are no lines or bars showing activity. The charts should appear empty.
