name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  test:
    name: "TestTestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testtestdriver
        with:
          prompt: |
            1. navigate to pubnub.com in google chrome
            2. click: LOGIN
            3. focus the email field and type: testdriver@email10p.org
            4. focus the password field and type: Testdriver@email10p.org
            5. press Return on the keyboard
            6. click Apps
            7. click My First App
            8. click Demo Keyset
            9. click Usage & Monitoring
            10. look at the charts, confirm there are is no data shown and the charts are empty
