name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          prompt: |
            1. navigate to "pubnub.com" in google chrome
            2. click "LOGIN"
            3. confirm login screen has an email and password field
            4. type in the email: "testdriver@email10p.org"
            5. type in the password: "Testdriver@email10p.org"
            6. click the red button labelled "LOG IN"
            7. click "Apps"
            8. click "My First App"
            9. click "Demo Keyset"
            10. click "Usage & Monitoring"
            11. confirm no usage shows on the charts
