name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          prompt: |
            1. navigate to pubnub.com in google chrome
            2. click: LOGIN
            3. type in the email: testdriver@email10p.org
            4. type in the password: Testdriver@email10p.org
            5. click the red button with label: LOG IN
            6. click: Apps
            7. click: My First App
            8. click: Demo Keyset
            9. click: Usage & Monitoring
            10. confirm no usage shows on the charts