name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# 1. type in the email: ${{ secrets.LOGIN_EMAIL }}
# 1. type in the password: ${{ secrets.LOGIN_PASSWORD }}
# 1. click LOG IN
# 1. click Apps
# 1. click My First App
# 1. click Demo Keyset
# 1. click Usage & Monitoring
# 1. confirm no usage shows on the charts

jobs:
  test:
    name: "TestTestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testtestdriver
        with:
          prompt: |
            1. navigate to pubnub.com in google chrome
            2. click LOGIN
            3. confirm login screen has an email and password field


            

            
