name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      hello: ${{ secrets.HELLO }}
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          prompt: |
            1. run this command 'echo $hello > ~/Desktop/result.txt'
            2. open the file located at '~/Desktop/result.txt'
            3. You're done test has passed!
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## TestDriver Summary
            ${{ steps.testdriver.outputs.summary }}